export interface QuizQuestion {
  scenario: string;
  question: string;
  options: string[];

  answerType?: "single" | "multiple";

  correctAnswer: string | string[];

  image?: string;

  explanation: string;
}

const quizQuestions: QuizQuestion[] = [
  {
    scenario: "A project has stable regulatory deliverables for a hardware subsystem but rapidly evolving customer feedback driving the companion mobile application. The sponsor insists on a single development approach for reporting simplicity, but the technical lead argues this would force one component to use an unsuitable method.",
    question: "What is the BEST recommendation?",
    options: [
      "Force both components into a purely predictive approach for consistency",
      "Let the sponsor's preference override the technical lead's concern",
      "Recommend a hybrid approach, tailored per component, and address reporting through consolidated status metrics",
      "Force both components into a purely adaptive approach for consistency",
    ],
    correctAnswer: "Recommend a hybrid approach, tailored per component, and address reporting through consolidated status metrics",
    explanation: "A hybrid approach tailored to each component's actual characteristics, with reporting complexity solved through consolidated metrics rather than a forced single method, addresses both the sponsor's reporting need and the technical reality; uniform predictive or adaptive approaches ignore genuine component differences.",
  },
  {
    scenario: "Three sprints into an agile transformation, velocity has stabilized, but a survey shows only 40% of developers can state the product vision without prompting. The scrum masters attribute this to competing local team goals set independently by each product owner. The project is approaching a major milestone, adding urgency to the situation.",
    question: "What should the project manager do FIRST?",
    options: [
      "Replace the product owners with a single centralized owner",
      "Instruct scrum masters to quiz developers on the vision weekly",
      "Facilitate alignment among product owners on a shared vision before addressing team-level goals",
      "Escalate the survey results to the PMO for corrective action",
    ],
    correctAnswer: "Facilitate alignment among product owners on a shared vision before addressing team-level goals",
    explanation: "The root cause is misaligned product owners, not the developers or scrum masters; aligning the owners on a shared vision first will cascade consistent messaging downward, whereas quizzing or escalating treats symptoms.",
  },
  {
    scenario: "",
    question: "A governance charter defines a $50,000 change approval threshold requiring escalation, but a sub-project manager recently approved a $48,000 change without escalation, then approved a related $15,000 change two weeks later, together exceeding the threshold, though neither individual approval technically violated the stated limit on its own, and the project manager only noticed the pattern by chance while reconciling the change log.",
    options: [
      "Retroactively cancel only the second, smaller change to bring the total under the threshold",
      "Clarify that related changes must be evaluated in aggregate against the threshold, and address the gap",
      "Raise the threshold significantly so this combination would not have required escalation",
      "Accept both approvals as compliant, since neither individually exceeded the threshold",
    ],
    correctAnswer: "Clarify that related changes must be evaluated in aggregate against the threshold, and address the gap",
    explanation: "Escalation thresholds meant to catch significant cumulative change require evaluating related changes in aggregate, not just individually; splitting a change to stay under a threshold, even unintentionally, undermines governance intent, unlike raising the threshold or retroactively cancelling only part of the work.",
  },
  {
    scenario: "During integration of five subsidiary plans, the project manager finds that the risk management plan assumes a schedule baseline that was superseded two weeks ago by an approved change, but no one updated the risk plan's assumptions to match. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Proceed with integration using the outdated risk assumptions, since the change was minor",
      "Integrate the plans as-is and flag the discrepancy for the next quarterly review",
      "Discard the risk management plan entirely and start over from scratch",
      "Reconcile the risk plan's assumptions with the current baseline before finalizing the integrated plan",
    ],
    correctAnswer: "Reconcile the risk plan's assumptions with the current baseline before finalizing the integrated plan",
    explanation: "Assessing consolidated plans for dependencies and gaps requires reconciling outdated assumptions against the current baseline before finalizing integration; proceeding with stale assumptions, discarding the plan, or deferring the fix all risk compounding the inconsistency.",
  },
  {
    scenario: "A program sponsor insists the vision statement remain unchanged despite a regulatory shift that has quietly invalidated one of its core assumptions. Two component project managers have already begun designing around the outdated assumption. Similar dynamics have surfaced on two other workstreams within the same program.",
    question: "What is the project manager's BEST course of action?",
    options: [
      "Continue as directed since the sponsor has final authority over the vision",
      "Present the regulatory evidence to the sponsor and recommend updating the vision before further design work",
      "Update the vision and inform the sponsor afterward",
      "Allow the component teams to design around the new regulation",
    ],
    correctAnswer: "Present the regulatory evidence to the sponsor and recommend updating the vision before further design work",
    explanation: "Keeping the vision current requires surfacing disconfirming evidence to decision- makers before proceeding; bypassing the sponsor or continuing on outdated assumptions both risk significant rework and governance failure.",
  },
  {
    scenario: "A three-point estimate for a critical activity yields optimistic = 8 days, most likely = 12 days, pessimistic = 22 days. Leadership has asked for a clear recommendation before the next governance review, given the potential downstream impact on other workstreams.",
    question: "Using the PERT beta distribution formula, what is the expected duration of this activity?",
    options: [
      "14 days",
      "13.33 days",
      "13 days",
      "15 days",
    ],
    correctAnswer: "13 days",
    explanation: "PERT expected duration = (O + 4M + P) / 6 = (8 + 48 + 22) / 6 = 13 days. Applying the standard weighted formula gives exactly 13 days, making it the correct expected duration for this activity.",
  },
  {
    scenario: "",
    question: "A steering committee's charter specifies quarterly governance reviews, but the committee has not actually convened in five months due to repeated member scheduling conflicts, while significant unapproved scope decisions have continued to be made informally by the project manager during this governance gap, with no documented rationale for any of them.",
    options: [
      "Escalate the governance lapse and pause significant informal decisions pending a resumed formal review",
      "Disband the steering committee",
      "Operating without governance reviews. The project has not yet failed",
      "Continue making informal decisions. The committee itself has failed to convene",
    ],
    correctAnswer: "Escalate the governance lapse and pause significant informal decisions pending a resumed formal review",
    explanation: "When formal governance meaningfully lapses, significant decisions should pause pending resumed oversight, and the lapse itself should be escalated; continuing informal decision-making indefinitely, accepting the status quo, or disbanding governance entirely all bypass necessary accountability.",
  },
  {
    scenario: "During a root-cause session about a vision misunderstanding, two explanations emerge with roughly equal supporting evidence: an ambiguous charter statement, and a translated regional office document that altered the original phrasing. The team has time to investigate only one before the next milestone. Stakeholders have started asking pointed questions about how this will be handled.",
    question: "What should the project manager do?",
    options: [
      "Investigate the translated document, since it directly reaches the confused stakeholders",
      "Skip investigation and reissue the original vision statement unchanged",
      "Investigate whichever explanation the sponsor believes is correct",
      "Investigate the charter ambiguity, since it is the original source document",
    ],
    correctAnswer: "Investigate the translated document, since it directly reaches the confused stakeholders",
    explanation: "Root-cause analysis should trace to the point closest to where the misunderstanding is actually occurring; since the translated document is what confused stakeholders directly encountered, it is the more actionable starting point despite the charter being the original source.",
  },
  {
    scenario: "A newly appointed project manager inherits a project where the integrated plan was never actually approved by two of the four required governance signatories, though work has proceeded for six weeks under the assumption that approval was merely a formality. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Pause new commitments and secure the missing formal approvals before proceeding further",
      "Retroactively mark the plan as approved",
      "Continue execution, since work has already proceeded without issue for six weeks",
      "Escalate to terminate the project due to the governance gap",
    ],
    correctAnswer: "Pause new commitments and secure the missing formal approvals before proceeding further",
    explanation: "An integrated plan lacking required formal approval creates real governance and accountability exposure regardless of how long work has proceeded; securing the missing approvals before further commitment is the appropriate corrective action, not continuing, faking approval, or an extreme termination response.",
  },
  {
    scenario: "",
    question: "An organization's standard project governance template includes a section for defining success metrics, but a new project's completed template lists only 'deliver on time' as its sole success metric, despite the project's business case citing measurable adoption and revenue targets as the primary drivers that justified funding the initiative in the first place.",
    options: [
      "Revise the success metrics to include the value-based targets actually cited in the business case",
      "Accept the single schedule-based metric, since the template has been completed",
      "Add the adoption and revenue targets if the project later falls behind schedule",
      "Remove the success metrics section from the template since it caused confusion",
    ],
    correctAnswer: "Revise the success metrics to include the value-based targets actually cited in the business case",
    explanation: "Defining success metrics as part of governance should genuinely reflect the value the business case seeks, not just default to schedule; revising to include the cited adoption and revenue targets closes this gap, unlike accepting an incomplete metric, conditional addition later, or removing the section altogether.",
  },
  {
    scenario: "A project's integrated plan was built assuming continued access to a specific cloud region, but a new corporate data-sovereignty policy released this week now prohibits that region for this project's data classification, invalidating a foundational architecture assumption made months ago. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Ignore the new policy until an audit specifically flags the violation",
      "Delegate the policy conflict to the legal department",
      "Continue using the prohibited region since switching now would be highly disruptive",
      "Reassess the affected assumption and update the integrated plan and dependent work accordingly",
    ],
    correctAnswer: "Reassess the affected assumption and update the integrated plan and dependent work accordingly",
    explanation: "Maintaining the integrated plan requires reassessing invalidated assumptions and updating dependent work promptly; ignoring the policy, continuing to violate it, or fully offloading responsibility without updating the plan all leave the project in continued noncompliance and risk.",
  },
  {
    scenario: "A hybrid project team includes a fixed-scope hardware stream and an iterative software stream. Software team members increasingly describe the project's purpose only in terms of sprint goals, losing sight of the integrated product vision the hardware team still references. This is the first time the issue has been raised through a formal channel.",
    question: "What should the project manager do?",
    options: [
      "Explicitly connect each sprint goal back to the overarching integrated product vision",
      "Require the software team to adopt the hardware team's planning cadence",
      "Remove vision discussion from software ceremonies to reduce meeting overhead",
      "Let each stream maintain its own separate vision since their methods differ",
    ],
    correctAnswer: "Explicitly connect each sprint goal back to the overarching integrated product vision",
    explanation: "In hybrid environments, iterative work must be explicitly tied back to the shared, overarching vision to prevent fragmentation; allowing separate visions or removing vision discussion would deepen the divide rather than promote a common vision.",
  },
  {
    scenario: "Consolidated data shows two subsidiary plans both claim ownership of the same $200,000 budget line for a shared testing environment, while no plan currently accounts for a newly required $60,000 security certification that was mandated after both plans were drafted. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Reconcile the budget overlap and the untracked certification cost as part of integration",
      "Split the disputed $200,000 evenly between the two subsidiary plans",
      "Leave both issues for the finance department to resolve",
      "Absorb the $60,000 certification cost from contingency reserve",
    ],
    correctAnswer: "Reconcile the budget overlap and the untracked certification cost as part of integration",
    explanation: "Assessing consolidated plans for dependencies, gaps, and continued business value means actively reconciling both the duplicated budget claim and the untracked new cost as part of integration; deferring, splitting arbitrarily, or partially addressing only one issue leaves real gaps unresolved.",
  },
  {
    scenario: "A key stakeholder consistently approves designs that subtly diverge from the agreed vision, always citing plausible short-term business justifications. Direct conversations have not changed the pattern over two months, and design debt is accumulating. Leadership has asked for a resolution before the next steering committee meeting.",
    question: "What should the project manager do NEXT?",
    options: [
      "Redefine the vision to match the pattern of approved designs",
      "Continue direct conversations indefinitely since the stakeholder always has a plausible reason",
      "Involve the sponsor in a structured review comparing accumulated decisions against the vision",
      "Unilaterally reverse the stakeholder's most recent design approval",
    ],
    correctAnswer: "Involve the sponsor in a structured review comparing accumulated decisions against the vision",
    explanation: "When informal alignment repeatedly fails despite plausible individual justifications, a structured, evidence-based review involving higher authority is needed to reveal the cumulative pattern, which no single conversation can address.",
  },
  {
    scenario: "",
    question: "A project's governance model assigns decision rights for technical architecture to a technical steering group, but a recent major architecture decision was instead made unilaterally by the project sponsor during an unrelated budget meeting, without technical steering group involvement or awareness, and the group only learned of the decision after implementation had already begun.",
    options: [
      "Escalate to remove the sponsor from the project for exceeding their defined authority",
      "Raise the governance deviation with the sponsor and route the decision through the defined technical process",
      "Accept the sponsor's decision as final",
      "Have the technical steering group ratify the decision after the fact",
    ],
    correctAnswer: "Raise the governance deviation with the sponsor and route the decision through the defined technical process",
    explanation: "Governance structures assigning specific decision rights should be respected even by senior stakeholders; raising the deviation and routing the decision through the properly defined process addresses the gap constructively, unlike simply deferring to seniority, silent after-the-fact ratification, or an extreme escalation.",
  },
  {
    scenario: "A steering committee wants a single execution strategy recommendation for a program combining a fixed-price government contract stream and an internally funded innovation stream with high requirements volatility, and has asked for the recommendation within 48 hours. The situation was only discovered during a routine review, not through any planned process.",
    question: "What should the project manager do?",
    options: [
      "Recommend identical governance and reporting cadences for both streams",
      "Recommend differentiated execution strategies per stream while aligning governance touchpoints where appropriate",
      "Recommend treating the entire program under the fixed-price contract's rules for consistency",
      "Recommend canceling the innovation stream since it complicates the execution strategy",
    ],
    correctAnswer: "Recommend differentiated execution strategies per stream while aligning governance touchpoints where appropriate",
    explanation: "Recommending a project execution strategy should reflect each stream's actual constraints, differentiating execution while still aligning governance touchpoints for coherent oversight; forcing identical treatment or eliminating a stream to simplify strategy ignores genuine, legitimate differences.",
  },
  {
    scenario: "A newly merged organization is running its first joint project. Legacy Company A's team describes success as feature completeness; legacy Company B's team describes success as adoption rate. Both definitions were informally inherited from prior employers and never reconciled for this project. A related concern was also raised informally during the previous status meeting.",
    question: "What should the project manager do?",
    options: [
      "Adopt whichever definition the more senior team members from Company A prefer",
      "Allow both definitions to coexist",
      "Facilitate a session to establish one shared definition of project success",
      "Postpone defining success until the merger integration is fully complete",
    ],
    correctAnswer: "Facilitate a session to establish one shared definition of project success",
    explanation: "A shared vision requires a single, facilitated, agreed definition of success; allowing divergent inherited definitions to persist, or defaulting to seniority, undermines the very alignment this task requires from the outset.",
  },
  {
    scenario: "A project manager is designing a governance model for a joint venture involving two partner organizations with historically different decision-making cultures, one highly centralized and one highly decentralized. Both partners have expressed willingness to compromise but disagree on the specifics.",
    question: "Select THREE elements essential to a workable governance model in this specific situation.",
    options: [
      "A single, informal verbal understanding between the two lead executives",
      "Defined escalation paths that account for both organizations' differing structures",
      "A governance model left deliberately vague to avoid early friction between the partners",
      "An assumption that one partner's existing internal governance model will simply be adopted by both",
      "Explicitly documented decision rights that both partner organizations have formally agreed to",
      "Clear success metrics jointly agreed upon by both partner organizations",
    ],
    answerType: "multiple",
    correctAnswer: [
      "Defined escalation paths that account for both organizations' differing structures",
      "Explicitly documented decision rights that both partner organizations have formally agreed to",
      "Clear success metrics jointly agreed upon by both partner organizations",
    ],
    explanation: "Explicitly documented, jointly agreed decision rights, escalation paths accounting for both structures, and jointly agreed success metrics are essential given the cultural mismatch. An informal verbal understanding, assuming one partner's model applies to both, and deliberate vagueness all invite the exact conflict this situation is prone to.",
  },
  {
    scenario: "A project manager is assessing a set of consolidated subsidiary plans ahead of baseline approval for a complex multi-vendor program, the largest the organization has undertaken this year. Several data points have been surfaced by the planning team during a structured review session.",
    question: "Select THREE data points that most directly indicate a genuine integration gap requiring resolution before baseline approval.",
    options: [
      "The team's chat tool displays messages in a different time zone than headquarters",
      "The communication plan lists one fewer distribution list than the RACI matrix",
      "Two subsidiary plans reference different, conflicting go-live dates for the same milestone",
      "The stakeholder register was formatted using a different font than other project documents",
      "The resource plan does not account for a dependency confirmed in the schedule plan",
      "The risk register assumes a vendor contract structure that was not actually selected",
    ],
    answerType: "multiple",
    correctAnswer: [
      "Two subsidiary plans reference different, conflicting go-live dates for the same milestone",
      "The resource plan does not account for a dependency confirmed in the schedule plan",
      "The risk register assumes a vendor contract structure that was not actually selected",
    ],
    explanation: "Conflicting milestone dates, a risk register built on an unselected contract structure, and an unaccounted-for resource dependency are substantive integration gaps that could cause real execution failures. Font formatting, chat tool time zone display, and a minor distribution list count difference are cosmetic and immaterial.",
  },
  {
    scenario: "Six weeks after a facilitated vision workshop that appeared successful, a pulse survey shows understanding has actually declined compared to the pre-workshop baseline. The project manager suspects the workshop's messaging did not survive translation into day-to-day work assignments. The situation has persisted for several weeks and is beginning to affect morale.",
    question: "What should the project manager do?",
    options: [
      "Investigate how the vision is being reinforced in daily work assignments and adjust accordingly",
      "Blame the survey methodology and disregard the declining trend",
      "Conclude that vision workshops are ineffective and discontinue them permanently",
      "Repeat the exact same workshop format, since it seemed successful initially",
    ],
    correctAnswer: "Investigate how the vision is being reinforced in daily work assignments and adjust accordingly",
    explanation: "A workshop alone does not sustain a vision; investigating whether reinforcement mechanisms in daily work are actually connecting people to the vision addresses the likely gap, rather than repeating a format or dismissing the data.",
  },
  {
    scenario: "A WBS dictionary entry describes a deliverable using language nearly identical to another entry two levels up in the hierarchy, and three team members interpret the scope of the lower- level entry completely differently as a result of this ambiguity. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Revise the ambiguous WBS dictionary entry to clearly differentiate it from the parent- level description",
      "Leave the WBS dictionary unchanged",
      "Remove the lower-level entry entirely and roll its scope into the parent level",
      "Assign the interpretation decision to whichever team member raised the issue first",
    ],
    correctAnswer: "Revise the ambiguous WBS dictionary entry to clearly differentiate it from the parent- level description",
    explanation: "Breaking down scope requires WBS dictionary entries with clear, non- overlapping descriptions; revising the ambiguous entry directly resolves the interpretation conflict, whereas leaving it unchanged, assigning arbitrary interpretation authority, or removing a legitimately distinct entry do not.",
  },
  {
    scenario: "Refer to the Cost Variance by Project Phase vs. Escalation Threshold chart. Execution Phase 2 shows variance exceeding the 10% escalation threshold, but the project manager's status report to the steering committee for that period does not mention any escalation. The steering committee only discovers the variance weeks later during an unrelated budget review.",
    question: "What is the MOST likely governance concern here?",
    options: [
      "The chart indicates the threshold itself was set incorrectly and should be raised",
      "The defined escalation threshold was not followed when it was clearly triggered in Execution Phase 2",
      "The chart is not reliable, since variance naturally fluctuates across project phases",
      "There is no concern, since the variance returned to acceptable levels in Execution Phase 3",
    ],
    image: "/quiz-images/pmp-complete/question-22.png",
    correctAnswer: "The defined escalation threshold was not followed when it was clearly triggered in Execution Phase 2",
    explanation: "A variance clearly exceeding the defined 10% threshold in Execution Phase 2 should have triggered formal escalation regardless of later improvement; the absence of any escalation mention indicates the governance policy was not followed, which is a genuine concern requiring investigation, not dismissal.",
  },
  {
    scenario: "A stakeholder signed off on the scope statement eight weeks ago but now claims their approval was based on a verbal summary from a delegate who has since left the organization, and the actual written scope statement was reportedly never personally reviewed by the signatory. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Disregard the stakeholder's claim since a signature exists on file",
      "Treat the original signature as fully binding",
      "Escalate the situation immediately to terminate the stakeholder's involvement in the project",
      "Review the documented scope directly with the stakeholder now to confirm genuine understanding and agreement",
    ],
    correctAnswer: "Review the documented scope directly with the stakeholder now to confirm genuine understanding and agreement",
    explanation: "Obtaining genuine stakeholder agreement on scope means ensuring actual understanding, not merely a signature obtained through a flawed process; reviewing the documented scope directly with the stakeholder now closes this credibility gap, unlike rigidly enforcing a questionable signature or an extreme escalation.",
  },
  {
    scenario: "A project manager is diagnosing why a previously well-understood vision has eroded over four months on a long-running transformation program. Several plausible contributing factors have been raised in a retrospective, and leadership wants a resolution before the next steering committee meeting.",
    question: "Select THREE factors that would most directly explain genuine vision erosion, as opposed to unrelated project issues.",
    options: [
      "The office relocating to a new building with better amenities",
      "A vendor invoice being paid two weeks later than scheduled",
      "Leadership turnover resulting in a new sponsor never formally briefed on the original vision",
      "A minor typo in the weekly status report template",
      "Incremental scope changes approved individually without revisiting alignment to the vision",
      "Onboarding of new team members without any vision-specific orientation",
    ],
    answerType: "multiple",
    correctAnswer: [
      "Leadership turnover resulting in a new sponsor never formally briefed on the original vision",
      "Incremental scope changes approved individually without revisiting alignment to the vision",
      "Onboarding of new team members without any vision-specific orientation",
    ],
    explanation: "Sponsor turnover without re-briefing, unreconciled incremental scope changes, and unoriented new hires are direct, well-documented mechanisms of vision erosion. Invoice timing, office relocation, and a report typo are unrelated administrative details with no bearing on vision.",
  },
  {
    scenario: "A product backlog item marked 'ready' for the next sprint has acceptance criteria that reference a downstream system behavior no one on the team has actually verified, and this gap is only discovered during sprint planning, one day before the sprint is scheduled to begin. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Include the item but assign it to the most experienced developer to compensate",
      "Pull the item from the sprint and complete refinement, including verification, before including it",
      "Proceed into the sprint as planned, since the item was already marked ready",
      "Split the acceptance criteria in half without verifying either portion beforehand",
    ],
    correctAnswer: "Pull the item from the sprint and complete refinement, including verification, before including it",
    explanation: "An item marked ready but containing unverified assumptions has not genuinely met the definition of ready; pulling it for proper refinement before the sprint begins prevents building against unconfirmed behavior, unlike proceeding anyway, over-relying on experience, or splitting criteria without resolving the gap.",
  },
  {
    scenario: "",
    question: "A compliance checklist confirms all required certifications are technically on file for a medical device project, but a closer date review reveals one critical certification expired four months ago and was never renewed, though the checklist still shows it as a completed, satisfied item, and the device is scheduled to ship to customers within the next two weeks.",
    options: [
      "Accept the checklist as satisfied, since the certification document does exist on file",
      "Wait until the next scheduled audit to address the expired certification",
      "Investigate the expired certification immediately and initiate renewal before further reliance on compliance status",
      "Remove the certification requirement from the checklist",
    ],
    correctAnswer: "Investigate the expired certification immediately and initiate renewal before further reliance on compliance status",
    explanation: "A checklist showing an expired certification as satisfied is dangerously misleading; immediately investigating and initiating renewal addresses genuine, current noncompliance exposure, unlike accepting the stale document, waiting for a future audit, or removing the requirement rather than fixing the actual gap.",
  },
  {
    scenario: "During sprint planning, a data scientist and a backend engineer disagree sharply about model deployment architecture. Both cite valid technical constraints, both have deep expertise in their respective domains, and the disagreement has recurred across three consecutive sprints without resolution. No prior corrective action has yet been attempted for this specific situation.",
    question: "What should the project manager do?",
    options: [
      "Force a decision based on whichever engineer has more seniority",
      "Alternate decision authority between the two engineers each sprint",
      "Facilitate a joint technical spike to generate shared data before deciding",
      "Avoid the topic in future plannings since it always causes friction",
    ],
    correctAnswer: "Facilitate a joint technical spike to generate shared data before deciding",
    explanation: "A recurring, evidence-based technical disagreement between two legitimate experts is best resolved by generating shared data through a joint spike, enabling collaborative problem-solving rather than an arbitrary authority-based or avoidance-based resolution.",
  },
  {
    scenario: "Two nearly simultaneous change requests would each independently expand scope by a similar, moderate amount, but approving both together would exceed the contingency reserve allocated for scope growth this quarter, and only one can realistically be approved without an additional funding request. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Approve both automatically, since each individually falls within normal approval limits",
      "Evaluate both against project value and stakeholder priority before deciding which to approve",
      "Approve whichever request was submitted first",
      "Reject both requests to avoid exceeding the contingency reserve",
    ],
    correctAnswer: "Evaluate both against project value and stakeholder priority before deciding which to approve",
    explanation: "Managing scope changes responsibly requires evaluating competing requests against value and priority when reserve capacity is genuinely constrained, rather than approving both by default, deciding purely by submission order, or rejecting both without evaluating their relative merit.",
  },
  {
    scenario: "A cost-conscious functional manager and a quality-focused project manager disagree over whether to proceed with a supplier despite a minor certification lapse. The functional manager wants to proceed to protect the schedule; the project manager wants to pause pending recertification. Both have valid organizational priorities at stake. This pattern has already been raised informally at least once before without resolution.",
    question: "What should the project manager do?",
    options: [
      "Force the functional manager's schedule priority since cost overruns are more visible to leadership",
      "Collaborate to jointly assess the actual risk exposure and agree on a data-driven path forward",
      "Escalate to the sponsor",
      "Compromise by proceeding with half of the planned order quantity",
    ],
    correctAnswer: "Collaborate to jointly assess the actual risk exposure and agree on a data-driven path forward",
    explanation: "When both parties have legitimate, non-trivial concerns and time permits, collaborating to jointly assess actual risk produces a durable, evidence-based resolution; compromise or forcing a side ignores the substance of the disagreement.",
  },
  {
    scenario: "",
    question: "Two applicable regulations impose conflicting requirements on the same data field, one mandates retention for seven years, the other mandates deletion after three years for the same category of data, and no one has yet determined which regulation takes precedence for this project's specific jurisdiction, leaving the data architecture team unable to finalize their retention design.",
    options: [
      "Avoid addressing the conflict, since both regulations technically remain unresolved",
      "Default to the longer retention period, since retaining data longer is generally safer",
      "Formally research and determine which regulation takes precedence before establishing the compliance approach",
      "Default to the shorter deletion period, since minimizing data held is generally safer",
    ],
    correctAnswer: "Formally research and determine which regulation takes precedence before establishing the compliance approach",
    explanation: "Genuinely conflicting regulatory requirements require formal research into precedence rather than an assumed default in either direction, since either default carries its own compliance risk; determining the actual applicable rule is necessary before establishing a defensible compliance approach.",
  },
  {
    scenario: "A WBS was decomposed to the work package level for all deliverables except one complex integration deliverable, which remains at a single high summary level because the responsible team insisted further decomposition was unnecessary for their specialized area of work. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Accept the team's judgment, since they have the most direct expertise in that area",
      "Remove the deliverable from the WBS",
      "Decompose the deliverables that are behind schedule",
      "Work with the team to decompose the deliverable further, since inconsistent decomposition undermines estimating and control",
    ],
    correctAnswer: "Work with the team to decompose the deliverable further, since inconsistent decomposition undermines estimating and control",
    explanation: "Consistent decomposition across the WBS is necessary for reliable estimating and control; an under-decomposed deliverable, even from a specialized team, creates a planning blind spot that should be addressed collaboratively, not accepted as-is, applied selectively, or avoided by removal.",
  },
  {
    scenario: "A team's ground rules prohibit interrupting during retrospectives, but a highly influential architect repeatedly interrupts junior engineers, and no one challenges the behavior because of the architect's seniority and technical reputation within the organization. Stakeholders have started asking pointed questions about how this will be handled. This is the first time the issue has been raised through a formal channel.",
    question: "What should the project manager do?",
    options: [
      "Move retrospectives to written, asynchronous format to avoid confrontation entirely",
      "Remove the interruption ground rule since it is clearly unenforceable in practice",
      "Address the ground rule violation directly and consistently, regardless of the architect's seniority",
      "Quietly ask junior engineers to be more assertive in future retrospectives",
    ],
    correctAnswer: "Address the ground rule violation directly and consistently, regardless of the architect's seniority",
    explanation: "Consistent enforcement of ground rules regardless of seniority is essential to a psychologically safe environment; shifting the burden to junior staff or abandoning the rule both fail to address the actual violation occurring.",
  },
  {
    scenario: "A client's signed statement of work references 'standard integration testing' without further definition, and the project team's internal standard for that phrase differs meaningfully from the client's own internal standard, a gap neither party noticed until testing was already underway. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Proceed using the client's standard without formally documenting the clarification",
      "Halt all testing indefinitely until legal counsel resolves the contractual ambiguity",
      "Clarify the actual expected standard with the client and formally document the agreed definition",
      "Proceed using the project team's internal standard, since the contract does not specify otherwise",
    ],
    correctAnswer: "Clarify the actual expected standard with the client and formally document the agreed definition",
    explanation: "Obtaining explicit stakeholder agreement on scope includes resolving genuinely ambiguous contractual language through clarification and documentation; unilaterally picking either party's assumed standard, or halting work entirely for an issue resolvable through direct clarification, are both disproportionate responses.",
  },
  {
    scenario: "",
    question: "A compliance audit trail shows evidence of quarterly reviews being conducted for the past year, but a forensic review of the underlying data reveals the same evidence file was resubmitted with only the date changed each quarter, meaning no actual review activity has genuinely occurred after the very first instance, despite the audit trail appearing fully compliant on the surface.",
    options: [
      "Accept the audit trail as sufficient, since documentation formally exists for each quarter",
      "Discipline the most recent submitter",
      "Discontinue quarterly reviews since the requirement has proven difficult to sustain",
      "Investigate the fabricated evidence and reestablish genuine quarterly review activity going forward",
    ],
    correctAnswer: "Investigate the fabricated evidence and reestablish genuine quarterly review activity going forward",
    explanation: "Fabricated compliance evidence is a serious integrity failure requiring investigation and genuine reestablishment of the actual review activity; accepting the paper trail at face value, disciplining only the most recent instance, or abandoning the requirement altogether all fail to address the real underlying problem.",
  },
  {
    scenario: "A project manager is reviewing a backlog refinement session for quality before sprint planning, after stakeholders raised visible concern about inconsistent readiness standards. Several items were discussed, and the team debated whether each genuinely met the definition of ready.",
    question: "Select THREE conditions that would indicate an item is NOT genuinely ready for sprint commitment.",
    options: [
      "The item was reviewed and confirmed feasible by at least one technical team member",
      "The item has been estimated by the team using an agreed relative sizing technique",
      "The item's business value has been clearly articulated and prioritized in the backlog",
      "The acceptance criteria reference a system behavior that has never actually been verified",
      "A dependency on another team's unfinished work has not yet been resolved",
      "The acceptance criteria are written in vague terms that different reviewers interpret differently",
    ],
    answerType: "multiple",
    correctAnswer: [
      "The acceptance criteria reference a system behavior that has never actually been verified",
      "A dependency on another team's unfinished work has not yet been resolved",
      "The acceptance criteria are written in vague terms that different reviewers interpret differently",
    ],
    explanation: "Unverified assumptions, unresolved cross-team dependencies, and vague, inconsistently interpreted acceptance criteria all indicate an item is not genuinely ready. Being estimated, having clear business value, and technical feasibility confirmation are positive indicators of readiness, not gaps.",
  },
  {
    scenario: "Two departments sharing a project have a low-stakes disagreement about which day each week to hold a routine status sync. The disagreement has consumed disproportionate discussion time relative to its importance, delaying more substantive agenda items in two consecutive meetings. The situation has persisted for several weeks and is beginning to affect morale.",
    question: "What should the project manager do?",
    options: [
      "Escalate the scheduling disagreement to the steering committee for a final ruling",
      "Make a quick unilateral decision on the day and move on to substantive items",
      "Cancel the routine status sync altogether to eliminate the recurring disagreement",
      "Facilitate an extended collaborative session specifically dedicated to resolving the scheduling issue",
    ],
    correctAnswer: "Make a quick unilateral decision on the day and move on to substantive items",
    explanation: "For low-stakes, time-sensitive disagreements, a quick decisive resolution preserves time for higher-value discussion; escalating or dedicating extended collaboration to a minor scheduling matter is disproportionate to its actual importance.",
  },
  {
    scenario: "",
    question: "A project operating under an environmental permit is approaching a production threshold that would trigger a stricter tier of regulatory obligations, but production forecasts suggest the threshold might be crossed mid-quarter, a possibility the compliance plan has never explicitly addressed or prepared for, leaving the team uncertain what additional obligations would actually apply.",
    options: [
      "Address the stricter obligations after the threshold has been crossed",
      "Assume the forecast is likely inaccurate and take no preparatory action",
      "Proactively prepare for the stricter tier now, given the credible forecast of crossing the threshold",
      "Deliberately throttle production to avoid ever crossing the threshold",
    ],
    correctAnswer: "Proactively prepare for the stricter tier now, given the credible forecast of crossing the threshold",
    explanation: "Determining the necessary approach to address compliance needs includes proactive preparation for a credibly forecasted threshold crossing, rather than waiting until after the fact, artificially constraining legitimate business activity without analysis, or dismissing a credible forecast without justification.",
  },
  {
    scenario: "Two backlog items have identical estimated development cost, but a recent customer survey shows Item X directly addresses the top-ranked customer pain point, while Item Y addresses a pain point ranked eighth out of ten. The product owner has been sequencing Item Y first purely by backlog age. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Defer both items until a more comprehensive value analysis can be completed",
      "Continue sequencing by backlog age, since it is the fairest and most consistent method",
      "Resequence to prioritize Item X first, given its significantly higher demonstrated customer value",
      "Deliver both items simultaneously in the same release to avoid resequencing at all",
    ],
    correctAnswer: "Resequence to prioritize Item X first, given its significantly higher demonstrated customer value",
    explanation: "Prioritizing work based on value and stakeholder feedback means resequencing toward the higher-value item once evidence is available; continuing to sequence purely by age, forcing simultaneous delivery, or deferring both ignore the clear survey evidence already in hand.",
  },
  {
    scenario: "A conflict between two vendor teams working on the same integration has escalated to public finger-pointing in a shared chat channel visible to the client. Initial analysis suggests both teams misunderstood an ambiguous interface specification differently, and neither acted in bad faith. The team has limited bandwidth this cycle to address anything beyond the immediate priority.",
    question: "What should the project manager do?",
    options: [
      "Ignore the chat exchange since the technical misunderstanding will eventually surface on its own",
      "Publicly clarify the ambiguous specification and privately address the tone of the exchange",
      "Terminate one vendor's contract to resolve the conflict decisively",
      "Ban both vendor teams from using the shared channel going forward",
    ],
    correctAnswer: "Publicly clarify the ambiguous specification and privately address the tone of the exchange",
    explanation: "Since the root cause was a genuinely ambiguous specification rather than misconduct, clarifying it publicly resolves the substance while addressing tone privately preserves both vendor relationships; termination and ignoring the visible conflict both fail to address the actual cause.",
  },
  {
    scenario: "A project delivered 100% of planned scope on schedule and within budget, but six months post-launch, the benefits realization tracking shows the target adoption rate has been reached by less than half, and no root-cause investigation into the gap has yet been initiated. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Attribute the low adoption entirely to factors outside the project's original scope",
      "Wait a further six months before taking any investigative action on adoption",
      "Consider the project fully successful. All original schedule and budget targets were met",
      "Investigate the adoption shortfall against the benefits realization plan and determine corrective options",
    ],
    correctAnswer: "Investigate the adoption shortfall against the benefits realization plan and determine corrective options",
    explanation: "Examining business value and verifying that a benefits measurement system tracks outcomes means actively investigating a significant realized shortfall, not declaring success based on schedule/budget alone, waiting further without action, or assuming the cause is automatically external.",
  },
  {
    scenario: "",
    question: "A newly hired compliance specialist flags that the project's existing compliance classification scheme conflates two genuinely distinct regulatory categories, safety and security, treating them as a single category, which has caused several security-specific requirements to be overlooked entirely in current planning documents, a gap only discovered during an external audit.",
    options: [
      "Accept the specialist's observation but defer any correction until the next project phase",
      "Correct the classification to properly separate the two categories and address the overlooked requirements",
      "Maintain the existing combined classification. Changing it now would require significant rework",
      "Dismiss the concern, since the combined classification has been used",
    ],
    correctAnswer: "Correct the classification to properly separate the two categories and address the overlooked requirements",
    explanation: "Classifying compliance categories correctly is foundational to catching all applicable requirements; correcting a conflated classification that has already caused specific requirements to be overlooked directly addresses a real, identified gap, unlike maintaining the status quo, deferring correction, or dismissing a valid new finding.",
  },
  {
    scenario: "A retrospective reveals that ground rule violations have been increasing steadily for six weeks, but each individual violation was minor enough that no one flagged it in the moment, and the cumulative erosion was only visible when reviewed in aggregate. This is the first time the issue has been raised through a formal channel.",
    question: "What should the project manager do?",
    options: [
      "Conclude that ground rules are unnecessary since no single incident was ever significant",
      "Reinforce ground rules and establish a lightweight mechanism to flag violations as they occur",
      "Assign one team member to be solely responsible for enforcing all ground rules",
      "Wait for a clearly significant violation before taking any corrective action",
    ],
    correctAnswer: "Reinforce ground rules and establish a lightweight mechanism to flag violations as they occur",
    explanation: "Cumulative minor violations require a real-time flagging mechanism to prevent gradual erosion from continuing unnoticed; waiting for a major incident or concluding rules are unnecessary both ignore the pattern already identified.",
  },
  {
    scenario: "A stakeholder group insists a specific feature must ship in the very next release because it was originally promised eighteen months ago, but market research completed last month shows that a different, unplanned feature would now generate roughly three times the projected customer value. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Honor the original promise regardless of the updated market research findings",
      "Deliver neither feature until stakeholders unanimously agree on a single path forward",
      "Silently substitute the higher-value feature without informing the stakeholders who were promised the original",
      "Present the updated value analysis to stakeholders and facilitate a re-prioritization discussion",
    ],
    correctAnswer: "Present the updated value analysis to stakeholders and facilitate a re-prioritization discussion",
    explanation: "Assessing opportunities to deliver value and prioritizing based on value and feedback requires transparently presenting new evidence to stakeholders for a re- prioritization discussion, rather than rigidly honoring an outdated promise, silently substituting without disclosure, or stalling indefinitely for full unanimity.",
  },
  {
    scenario: "A long-simmering interpersonal conflict between two senior stakeholders predates the current project by several years and stems from an unrelated prior organizational restructuring. Their disagreement is now affecting a joint decision the project urgently needs within 48 hours. This pattern has already been raised informally at least once before without resolution.",
    question: "What should the project manager do?",
    options: [
      "Wait for the stakeholders to resolve their years-long history before requesting the decision",
      "Ask a third stakeholder unfamiliar with the situation to simply make the decision alone",
      "Facilitate a narrowly scoped conversation focused only on the urgent decision, separate from history",
      "Escalate the entire historical conflict to HR for mediation before proceeding",
    ],
    correctAnswer: "Facilitate a narrowly scoped conversation focused only on the urgent decision, separate from history",
    explanation: "Given the urgent deadline, narrowly scoping the conversation to the immediate decision, while acknowledging but not attempting to resolve unrelated historical conflict, is the pragmatic approach; waiting or full HR mediation would miss the deadline.",
  },
  {
    scenario: "A project manager is designing a compliance monitoring approach for a project subject to several overlapping and evolving regulatory frameworks. The organization has historically relied on a single annual audit.",
    question: "Select THREE practices that would most effectively support genuine, ongoing compliance rather than a one-time, point-in-time check that quickly becomes outdated.",
    options: [
      "Establishing recurring audits and reviews rather than relying on a single initial assessment",
      "Treating all regulatory categories as equally low-priority to simplify monitoring effort",
      "Relying primarily on informal personal knowledge of team members to catch regulatory changes",
      "Assuming that once a regulation is addressed, it will never require reassessment",
      "Maintaining verifiable, current evidence rather than static, potentially outdated documentation",
      "Actively monitoring for regulatory changes that could affect previously satisfied requirements",
    ],
    answerType: "multiple",
    correctAnswer: [
      "Establishing recurring audits and reviews rather than relying on a single initial assessment",
      "Maintaining verifiable, current evidence rather than static, potentially outdated documentation",
      "Actively monitoring for regulatory changes that could affect previously satisfied requirements",
    ],
    explanation: "Recurring audits, active monitoring for regulatory changes, and maintaining current verifiable evidence all support genuine ongoing compliance. Assuming permanence, relying on informal personal knowledge, and treating all categories as equally low priority all undermine a genuinely proactive compliance monitoring approach.",
  },
  {
    scenario: "A team has been delivering working increments every two weeks for the past four months, but a recent stakeholder interview reveals none of the increments have actually been used in production, since the client's own internal deployment approval process takes considerably longer than the delivery cadence. This has already caused visible concern among stakeholders.",
    question: "What should the project manager do?",
    options: [
      "Slow the team's delivery cadence dramatically to match the client's slower approval process",
      "Continue the current delivery cadence unchanged, since the team is meeting its internal targets",
      "Evaluate delivery options with the client to align cadence with their actual deployment capacity",
      "Conclude that incremental delivery is not suitable for this client and revert to a single final release",
    ],
    correctAnswer: "Evaluate delivery options with the client to align cadence with their actual deployment capacity",
    explanation: "Evaluating delivery options to demonstrate real value requires aligning cadence with the client's actual capacity to realize that value, rather than continuing unchanged, arbitrarily slowing to match without discussion, or abandoning incremental delivery entirely based on a solvable coordination issue.",
  },
  {
    scenario: "A benefits realization dashboard was set up at project initiation to track three key metrics, but a mid-project review reveals one metric has never actually had any data populated because the source system integration required to capture it was never completed. This pattern has now repeated across two consecutive reporting cycles without resolution.",
    question: "What should the project manager do?",
    options: [
      "Prioritize completing the missing integration or find an alternate way to capture the metric",
      "Estimate the missing metric's value informally without any actual underlying data",
      "Leave the metric blank, since two of the three metrics are still being tracked",
      "Remove the metric from the dashboard entirely, since it cannot currently be measured",
    ],
    correctAnswer: "Prioritize completing the missing integration or find an alternate way to capture the metric",
    explanation: "Verifying that a measurement system is genuinely in place to track benefits means addressing a metric that has never actually been captured, either by completing the integration or finding an alternate capture method, rather than leaving it blank, removing it, or fabricating estimates.",
  },
  {
    scenario: "A project manager is coaching a new team lead, ahead of a major upcoming milestone, on selecting conflict resolution strategies appropriate to different situations, since a similar coaching session was never conducted for the previous team lead. The team lead presents six scenario descriptions and must correctly match strategy to context.",
    question: "Select THREE scenario- strategy pairings that are appropriate.",
    options: [
      "Using withdrawing/avoiding as the default response to every conflict that arises on the team",
      "Using collaborating when both parties have valid, significant concerns and time allows for joint problem-solving",
      "Using smoothing to temporarily preserve a relationship during a high-pressure moment, with follow-up planned later",
      "Using forcing whenever any two team members disagree about anything, regardless of stakes",
      "Using compromising for a low-stakes, time-sensitive disagreement where a quick middle-ground resolution suffices",
      "Using forcing in a genuine safety-critical emergency requiring an immediate, non- negotiable decision",
    ],
    answerType: "multiple",
    correctAnswer: [
      "Using collaborating when both parties have valid, significant concerns and time allows for joint problem-solving",
      "Using compromising for a low-stakes, time-sensitive disagreement where a quick middle-ground resolution suffices",
      "Using forcing in a genuine safety-critical emergency requiring an immediate, non- negotiable decision",
    ],
    explanation: "Collaborating fits significant mutual concerns with time available; compromising fits low-stakes, time-sensitive issues; forcing fits genuine emergencies. Forcing or avoiding as a blanket default, and smoothing without follow-up, misapply strategies to inappropriate contexts.",
  },
  {
    scenario: "",
    question: "A change control board approves a change with a specific implementation date, but the development team implements it two weeks early, unaware of a dependency that had been specifically timed to prevent conflict with a separate, ongoing data migration effort scheduled during those exact same two weeks, and the resulting conflict corrupted a portion of the migrated data.",
    options: [
      "Retroactively approve the early implementation",
      "Address the deviation from the approved timing, given the dependency conflict it created with the migration",
      "Ignore the timing deviation entirely",
      "Accept the early implementation as beneficial. The change was completed sooner than required",
    ],
    correctAnswer: "Address the deviation from the approved timing, given the dependency conflict it created with the migration",
    explanation: "Approved change control includes approved timing, not just approved content; implementing early without regard to a known dependency created a real conflict that must be addressed, rather than being excused as beneficial, retroactively rubber-stamped, or ignored because the underlying change was approved.",
  },
  {
    scenario: "A product owner wants to demonstrate the project's value to a skeptical new executive sponsor who was not involved during the project's first year. Three options are available: a slide deck of planned features, a live demo of working functionality with real usage data, or a Gantt chart showing schedule adherence.",
    question: "What should the project manager do?",
    options: [
      "Present the live demo with real usage data, since it directly evidences realized value",
      "Present all three simultaneously without any particular emphasis on any single one",
      "Present the Gantt chart, since schedule adherence is the clearest indicator of project discipline",
      "Present the slide deck of planned features, since it is the quickest option to prepare",
    ],
    correctAnswer: "Present the live demo with real usage data, since it directly evidences realized value",
    explanation: "Evaluating delivery options to demonstrate value favors evidence of realized value, such as a live demo with real usage data, over a schedule-focused artifact or a plan- only slide deck; presenting everything without emphasis dilutes the specific, persuasive evidence a skeptical sponsor needs.",
  },
];

export default quizQuestions;
